import json
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from core.database import get_db
from models.behavior_metrics import BehaviorMetrics, BehaviorMetricsCRUD
from models.lead_application import LeadApplication, LeadApplicationCRUD
from schemas.behavior_metrics import BehaviorMetricsCreate, BehaviorMetricsRead, BehaviorMetricsUpdate

router = APIRouter(prefix="/behavior-metrics", tags=["behavior-metrics"])


@router.post("", response_model=BehaviorMetricsRead, status_code=status.HTTP_201_CREATED)
def create_behavior_metrics(payload: dict[str, Any], db: Session = Depends(get_db)) -> BehaviorMetrics:
    application_id = int(payload.get("application_id", 0) or 0)
    time_on_page_seconds = int(payload.get("time_on_page_seconds", payload.get("time_on_page", 0)) or 0)

    raw_clicks = payload.get("button_clicks", payload.get("buttons_clicked", []))
    if isinstance(raw_clicks, str):
        button_clicks: list[str] | dict[str, Any] = [x for x in raw_clicks.split("|") if x]
    elif isinstance(raw_clicks, dict):
        button_clicks = raw_clicks
    elif isinstance(raw_clicks, list):
        button_clicks = raw_clicks
    else:
        button_clicks = []

    raw_positions = payload.get("cursor_hover_zones", payload.get("cursor_positions", []))
    cursor_hover_zones: list[dict[str, int]]
    if isinstance(raw_positions, str):
        parsed = []
        stripped = raw_positions.strip()
        if stripped.startswith("["):
            try:
                parsed_json = json.loads(stripped)
                if isinstance(parsed_json, list):
                    parsed = parsed_json
            except json.JSONDecodeError:
                parsed = []
        else:
            # Legacy формат: "sec:x,y;..."
            for sample in stripped.split(";"):
                if ":" not in sample:
                    continue
                sec_raw, xy_raw = sample.split(":", 1)
                if "," not in xy_raw:
                    continue
                x_raw, y_raw = xy_raw.split(",", 1)
                try:
                    sec = int(sec_raw)
                    x = int(x_raw)
                    y = int(y_raw)
                except ValueError:
                    continue
                parsed.append({"x": x, "y": y, "timestamp": sec})
        cursor_hover_zones = [
            {"x": int(item.get("x", 0)), "y": int(item.get("y", 0)), "timestamp": int(item.get("timestamp", 0))}
            for item in parsed
            if isinstance(item, dict)
        ]
    elif isinstance(raw_positions, list):
        cursor_hover_zones = [
            {"x": int(item.get("x", 0)), "y": int(item.get("y", 0)), "timestamp": int(item.get("timestamp", 0))}
            for item in raw_positions
            if isinstance(item, dict)
        ]
    elif isinstance(raw_positions, dict):
        cursor_hover_zones = [
            {
                "x": int(raw_positions.get("x", 0)),
                "y": int(raw_positions.get("y", 0)),
                "timestamp": int(raw_positions.get("timestamp", 0)),
            }
        ]
    else:
        cursor_hover_zones = []

    return_visits_count = int(payload.get("return_visits_count", payload.get("return_frequency", 0)) or 0)
    technical_payload = payload.get("technical_payload", {})
    if not isinstance(technical_payload, dict):
        technical_payload = {}

    # Потоковая телеметрия может приходить с application_id=0.
    # Обеспечиваем наличие служебной заявки с id=0 для соблюдения FK.
    if application_id <= 0 and LeadApplicationCRUD.get_by_id(db, 0) is None:
        stub = LeadApplication(
            id=0,
            first_name="system",
            last_name="telemetry",
            patronymic=None,
            business_info="autogenerated telemetry row",
            business_niche="telemetry",
            company_size="unknown",
            task_volume="unknown",
            role="system",
            business_size="unknown",
            need_volume="unknown",
            result_deadline="unknown",
            task_type="telemetry",
            interested_product="telemetry",
            budget="0",
            preferred_contact_method="system",
            convenient_time="always",
            comments="Created automatically for behavior metrics stream",
        )
        LeadApplicationCRUD.create(db, obj=stub)

    if application_id <= 0:
        application_id = 0

    data = BehaviorMetricsCreate(
        application_id=application_id,
        time_on_page_seconds=time_on_page_seconds,
        button_clicks=button_clicks,
        cursor_hover_zones=cursor_hover_zones,
        return_visits_count=return_visits_count,
        technical_payload=technical_payload,
    ).model_dump()
    entity = BehaviorMetrics(**data)
    return BehaviorMetricsCRUD.create(db, obj=entity)


@router.get("", response_model=list[BehaviorMetricsRead])
def list_behavior_metrics(
    skip: int = 0, limit: int = 100, db: Session = Depends(get_db)
) -> list[BehaviorMetrics]:
    return BehaviorMetricsCRUD.list_all(db, skip=skip, limit=limit)


@router.get("/{application_id}", response_model=BehaviorMetricsRead)
def get_behavior_metrics(application_id: int, db: Session = Depends(get_db)) -> BehaviorMetrics:
    row = BehaviorMetricsCRUD.get_by_application_id(db, application_id)
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Metrics not found")
    return row


@router.put("/{application_id}", response_model=BehaviorMetricsRead)
def update_behavior_metrics(
    application_id: int, payload: BehaviorMetricsUpdate, db: Session = Depends(get_db)
) -> BehaviorMetrics:
    row = BehaviorMetricsCRUD.get_by_application_id(db, application_id)
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Metrics not found")
    for key, value in payload.model_dump(exclude_unset=True).items():
        setattr(row, key, value)
    return BehaviorMetricsCRUD.update(db, row)


@router.delete("/{application_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_behavior_metrics(application_id: int, db: Session = Depends(get_db)) -> None:
    row = BehaviorMetricsCRUD.get_by_application_id(db, application_id)
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Metrics not found")
    BehaviorMetricsCRUD.delete(db, row)
